#!/usr/bin/env node
/**
 * Validates every GraphQL operation this app sends against the gateway's
 * schema (server/app/api-gateway/src/schema.gql).
 *
 * ## Why this exists
 *
 * `recordedBy { id name }` shipped in `modules/readings/services/operations.ts`
 * against a `ReadingRecordedByType` that has `firstname` + `lastname` and no
 * `name`. Because that field list is shared by the readings *query* and the
 * create *mutation*, the gateway rejected both at validation — before any
 * resolver ran — and the app presented it as two unrelated bugs: history that
 * never loaded, and readings stuck in the queue forever.
 *
 * Nothing could have caught it. TypeScript sees a template string. Jest mocks
 * the transport, so all 377 tests passed over a query the server refuses. The
 * schema is the only thing that knows, and it lives in another app.
 *
 * ## What it does and does not check
 *
 * Operations are validated as documents: field existence, argument names,
 * variable types, selection-set shape. It does **not** check that the
 * *response* is mapped correctly — a query can be valid and still be read
 * wrong by `lib/mappers.ts`, which is what unit tests are for.
 *
 * `${FRAGMENT}` interpolation is resolved against same-file template consts
 * first. Skipping those would skip the readings operations specifically,
 * which are the ones that broke.
 *
 * ## Reading the schema from another app
 *
 * `src/schema.gql` is generated by Nest's `autoSchemaFile` on gateway boot,
 * so a stale checkout means a stale answer. That is the trade: this catches
 * a client that disagrees with the *committed* schema, cheaply, on every
 * `pnpm check`. Catching a client that disagrees with a *running* gateway
 * needs the gateway running — see `docs/todo/CI-graphql-contract.md`.
 *
 * Same cross-app read as `verify-models.mjs`, for the same reason: the
 * contract has one owner and it is not this app.
 *
 * Exit codes: 0 all valid · 1 at least one invalid · 2 cannot check
 * (schema missing).
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildSchema, parse, validate } from 'graphql';

const here = dirname(fileURLToPath(import.meta.url));
const clientSrc = resolve(here, '..', 'src');
const schemaPath = resolve(
  here,
  '..',
  '..',
  'server',
  'app',
  'api-gateway',
  'src',
  'schema.gql',
);

if (!existsSync(schemaPath)) {
  // A client-only checkout is a legitimate way to work on this app, and
  // failing the gate for it would teach people to skip the gate.
  console.warn(
    `[verify-graphql] schema not found at ${schemaPath} — skipping.\n` +
      '  The gateway generates it on boot (pnpm --dir server/app/api-gateway start:dev).',
  );
  process.exit(0);
}

let schema;
try {
  schema = buildSchema(readFileSync(schemaPath, 'utf8'));
} catch (error) {
  console.error(`[verify-graphql] could not parse ${schemaPath}: ${error.message}`);
  process.exit(2);
}

function* sourceFiles(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* sourceFiles(full);
    else if (/\.(ts|tsx)$/.test(entry.name) && !entry.name.includes('.test.')) yield full;
  }
}

/** `const FOO = \`…\`` — the fragments operations interpolate. */
const TEMPLATE_CONST = /(?:const|let|var)\s+([A-Za-z0-9_]+)\s*=\s*`([^`]*)`/g;

/** A template literal holding a top-level operation. */
const OPERATION = /`([^`]*\b(?:query|mutation|subscription)\s+[A-Za-z0-9_]*\s*[({][^`]*)`/g;

const MAX_INTERPOLATION_DEPTH = 5;

function resolveInterpolation(body, consts, depth = 0) {
  if (depth >= MAX_INTERPOLATION_DEPTH || !body.includes('${')) return body;

  const next = body.replace(/\$\{\s*([A-Za-z0-9_]+)\s*\}/g, (whole, name) =>
    consts[name] === undefined ? whole : consts[name],
  );
  return next === body ? next : resolveInterpolation(next, consts, depth + 1);
}

const operationName = (body) =>
  body.match(/\b(?:query|mutation|subscription)\s+([A-Za-z0-9_]+)/)?.[1] ?? '(anonymous)';

let checked = 0;
let invalid = 0;
let skipped = 0;

for (const file of sourceFiles(clientSrc)) {
  const source = readFileSync(file, 'utf8');
  const where = relative(resolve(here, '..'), file);

  const consts = Object.fromEntries(
    [...source.matchAll(TEMPLATE_CONST)].map(([, name, value]) => [name, value]),
  );

  for (const [, raw] of source.matchAll(OPERATION)) {
    const body = resolveInterpolation(raw, consts);

    // An operation built from a value this script cannot see is reported
    // rather than silently passed — an unchecked query is the state that
    // produced the bug in the first place.
    if (body.includes('${')) {
      skipped += 1;
      console.warn(`?  ${where} → ${operationName(body)}: unresolved interpolation, not checked`);
      continue;
    }

    let document;
    try {
      document = parse(body);
    } catch {
      // Not a standalone document (a bare fragment, a string that merely
      // contains the word "query"). Nothing to validate.
      continue;
    }

    checked += 1;

    const errors = validate(schema, document);
    if (errors.length === 0) continue;

    invalid += 1;
    console.error(`\n✗ ${where} → ${operationName(body)}`);
    for (const error of errors) console.error(`    ${error.message}`);
  }
}

const summary = `checked ${checked} operations, ${invalid} invalid, ${skipped} unchecked`;

if (invalid > 0) {
  console.error(
    `\n${summary}\n` +
      'The gateway rejects these before any resolver runs. The schema is\n' +
      'generated from server/app/api-gateway/src/reading/*.resolver.ts and\n' +
      'friends — fix the client selection, or regenerate the schema if the\n' +
      'gateway changed.',
  );
  process.exit(1);
}

console.log(`[verify-graphql] ${summary}`);
