import { useMigrations } from 'drizzle-orm/expo-sqlite/migrator';

// Generated by `pnpm drizzle-kit generate`. The .sql files it imports are
// inlined as strings by babel-plugin-inline-import — see babel.config.js.
import migrations from '../../drizzle/migrations';

import { getDb } from './index';

export type MigrationState = {
  /** True once every pending migration has been applied. */
  success: boolean;
  error?: Error;
};

/**
 * Applies pending migrations on app start.
 *
 * Deliberately not fire-and-forget: the UI must not read from tables that do
 * not exist yet, so callers gate rendering on `success`. A failure here is
 * not recoverable in-app — the local database is unusable — so it surfaces
 * rather than being swallowed.
 */
export function useDatabaseMigrations(): MigrationState {
  return useMigrations(getDb(), migrations);
}
