#!/bin/sh
# docker-entrypoint.sh — Fetch (and verify) the OCR model artifacts from R2
# before handing off to the FastAPI CMD.
#
# The Docker image no longer ships any *.onnx / *.npz weights — they are
# downloaded on first boot into $MODELS_DIR and reused on subsequent boots.
# When a Compose volume is mounted at $MODELS_DIR (see infra/docker-compose),
# the download cost is paid once per host.
#
# Contract:
#   - models/EXPECTED_HASHES.json is the source of truth: keys are filenames,
#     values are sha256 hex digests. Generated by the maintainer who uploaded
#     the artifacts to R2.
#   - For every entry: if the file is missing OR its sha256 mismatches the
#     expected value, we re-download from $AI_MODELS_R2_BASE_URL/<filename>
#     and verify the hash again. Any final mismatch is a refuse-to-start
#     condition — a stale model on disk silently corrupts every reading.
#   - crnn.pt (training-source artifact) is NOT in the manifest and is NOT
#     fetched here.
#
# POSIX sh on purpose — the slim base image isn't guaranteed to have bash.

set -eu

MODELS_DIR="${MODELS_DIR:-/app/models}"
HASH_FILE="${HASH_FILE:-/app/models/EXPECTED_HASHES.json}"
PLACEHOLDER_URL="https://REPLACE_ME.r2.dev/bp-monitor/models"

if [ -z "${AI_MODELS_R2_BASE_URL:-}" ]; then
    echo "ERROR: AI_MODELS_R2_BASE_URL is not set." >&2
    echo "       Set it to the public R2 base URL hosting the model artifacts," >&2
    echo "       e.g. https://<account>.r2.dev/bp-monitor/models" >&2
    exit 1
fi

if [ "$AI_MODELS_R2_BASE_URL" = "$PLACEHOLDER_URL" ]; then
    echo "ERROR: AI_MODELS_R2_BASE_URL is still the placeholder ($PLACEHOLDER_URL)." >&2
    echo "       Replace it with the real R2 base URL before starting the service." >&2
    exit 1
fi

if [ ! -f "$HASH_FILE" ]; then
    echo "ERROR: hash manifest not found at $HASH_FILE" >&2
    exit 1
fi

mkdir -p "$MODELS_DIR"

# Strip a trailing slash from the base URL so concatenation stays clean.
BASE_URL="${AI_MODELS_R2_BASE_URL%/}"

# Emit "filename<TAB>expected_sha256" lines from the JSON manifest. Using the
# already-present python interpreter keeps us off jq.
FILE_LIST="$(python -c '
import json, sys
with open(sys.argv[1]) as f:
    for name, digest in json.load(f).items():
        print(f"{name}\t{digest}")
' "$HASH_FILE")"

compute_sha256() {
    # Print only the hex digest (sha256sum prefixes "<digest>  <path>").
    sha256sum "$1" | awk '{print $1}'
}

# Process each manifest entry. We use a here-string via a heredoc so the
# `while read` loop runs in the *current* shell — piping into the loop would
# spawn a subshell on POSIX sh and `exit 1` inside it would not abort the
# script. POSIX-safe IFS handling so the literal tab splits cleanly.
TAB="$(printf '\t')"
while IFS="$TAB" read -r filename expected; do
    [ -z "$filename" ] && continue
    target="$MODELS_DIR/$filename"

    if [ -f "$target" ]; then
        actual="$(compute_sha256 "$target")"
        if [ "$actual" = "$expected" ]; then
            echo "models: $filename ok (cached)"
            continue
        fi
        echo "models: $filename sha256 mismatch (have $actual, expected $expected); re-downloading" >&2
        rm -f "$target"
    else
        echo "models: $filename missing; downloading"
    fi

    url="$BASE_URL/$filename"
    if ! curl --fail --silent --show-error --retry 3 --retry-delay 2 -o "$target" "$url"; then
        echo "ERROR: failed to download $filename from $url" >&2
        rm -f "$target"
        exit 1
    fi

    actual="$(compute_sha256 "$target")"
    if [ "$actual" != "$expected" ]; then
        echo "ERROR: $filename downloaded but sha256 mismatch (have $actual, expected $expected)" >&2
        rm -f "$target"
        exit 1
    fi
    echo "models: $filename ok (downloaded)"
done <<EOF
$FILE_LIST
EOF

echo "models: all artifacts verified in $MODELS_DIR"

exec "$@"
